# Generated by Django 5.1.3 on 2024-11-26 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="assignees",
            field=models.ManyToManyField(
                related_name="assigned_todo", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
